#!/usr/bin/env python3
"""
Kaggle Training Script - Generates and pushes ML notebooks
For apps that require machine learning model training
"""

import os
import sys
import json
from pathlib import Path
from datetime import datetime

# Check optional environment variables
KAGGLE_USERNAME = os.environ.get("KAGGLE_USERNAME")
KAGGLE_KEY = os.environ.get("KAGGLE_KEY")

kaggle_connected = bool(KAGGLE_USERNAME and KAGGLE_KEY)

try:
    from git import Repo
except ImportError:
    print("⚠️  Warning: gitpython not installed")
    print("   Run: pip install gitpython")
    Repo = None

# Parse arguments
if len(sys.argv) < 2:
    print("Usage: python3 kaggle_train.py <app-slug> [ml-task-description]")
    sys.exit(1)

app_slug = sys.argv[1]
ml_description = sys.argv[2] if len(sys.argv) > 2 else "Machine learning model training"

app_path = Path(f"apps/{app_slug}")

if not app_path.exists():
    print(f"❌ Error: App directory not found: {app_path}")
    sys.exit(1)

print(f"🤖 ML Training Setup for: {app_slug}")
print(f"📝 Task: {ml_description}")
print(f"🔑 Kaggle API: {'Connected' if kaggle_connected else 'Not connected'}")
print("-" * 50)

# Generate a standard Kaggle notebook template
notebook = {
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        },
        "kaggle": {
            "accelerator": "nvidiaTeslaT4",
            "dataSources": [],
            "dockerImageVersionId": 30733,
            "isGpuEnabled": True,
            "isInternetEnabled": True,
            "language": "python",
            "sourceType": "notebook"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Create notebook cells
cells = []

# Cell 1: Introduction
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        f"# {app_slug.replace('-', ' ').title()} - ML Training\n",
        "\n",
        f"**Generated by AI App Builder**\n",
        f"\n",
        f"**Task:** {ml_description}\n",
        f"\n",
        f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    ]
})

# Cell 2: Setup
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Install required packages\n",
        "!pip install pandas numpy scikit-learn matplotlib seaborn\n",
        "\n",
        "# Import libraries\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix\n",
        "\n",
        "print('✅ Libraries loaded successfully')"
    ],
    "outputs": []
})

# Cell 3: Load Data
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Load your dataset\n",
        "# Update this path based on your uploaded data\n",
        "df = pd.read_csv('data/train.csv')\n",
        "\n",
        "print(f'Dataset shape: {df.shape}')\n",
        "df.head()"
    ],
    "outputs": []
})

# Cell 4: EDA
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Exploratory Data Analysis\n",
        "print(df.info())\n",
        "print('\\nMissing values:')\n",
        "print(df.isnull().sum())\n",
        "print('\\nTarget distribution:')\n",
        "df['target'].value_counts().plot(kind='bar')\n",
        "plt.title('Target Distribution')\n",
        "plt.show()"
    ],
    "outputs": []
})

# Cell 5: Preprocessing
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Data Preprocessing\n",
        "# Separate features and target\n",
        "X = df.drop('target', axis=1)\n",
        "y = df['target']\n",
        "\n",
        "# Handle missing values\n",
        "X = X.fillna(X.mean(numeric_only=True))\n",
        "\n",
        "# Split data\n",
        "X_train, X_test, y_train, y_test = train_test_split(\n",
        "    X, y, test_size=0.2, random_state=42, stratify=y\n",
        ")\n",
        "\n",
        "# Scale features\n",
        "scaler = StandardScaler()\n",
        "X_train = scaler.fit_transform(X_train)\n",
        "X_test = scaler.transform(X_test)\n",
        "\n",
        "print(f'Training set: {X_train.shape}')\n",
        "print(f'Test set: {X_test.shape}')"
    ],
    "outputs": []
})

# Cell 6: Model Training
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Train Model\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "\n",
        "# Initialize and train\n",
        "model = RandomForestClassifier(n_estimators=100, random_state=42)\n",
        "model.fit(X_train, y_train)\n",
        "\n",
        "print('✅ Model trained successfully')"
    ],
    "outputs": []
})

# Cell 7: Evaluation
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Evaluate Model\n",
        "y_pred = model.predict(X_test)\n",
        "\n",
        "print(f'Accuracy: {accuracy_score(y_test, y_pred):.4f}')\n",
        "print('\\nClassification Report:')\n",
        "print(classification_report(y_test, y_pred))\n",
        "\n",
        "# Confusion Matrix\n",
        "plt.figure(figsize=(8, 6))\n",
        "sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues')\n",
        "plt.title('Confusion Matrix')\n",
        "plt.ylabel('Actual')\n",
        "plt.xlabel('Predicted')\n",
        "plt.show()"
    ],
    "outputs": []
})

# Cell 8: Save Model
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Save the trained model\n",
        "import joblib\n",
        "\n",
        "joblib.dump(model, 'model.pkl')\n",
        "joblib.dump(scaler, 'scaler.pkl')\n",
        "\n",
        "print('✅ Model saved as model.pkl')\n",
        "print('✅ Scaler saved as scaler.pkl')"
    ],
    "outputs": []
})

# Cell 9: Inference Example
cells.append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "source": [
        "# Example: Make predictions on new data\n",
        "# Load model and scaler\n",
        "model = joblib.load('model.pkl')\n",
        "scaler = joblib.load('scaler.pkl')\n",
        "\n",
        "# Example prediction (replace with actual data)\n",
        "sample = X_test[:5]\n",
        "predictions = model.predict(sample)\n",
        "probabilities = model.predict_proba(sample)\n",
        "\n",
        "print('Sample predictions:', predictions)\n",
        "print('Confidence:', probabilities.max(axis=1))"
    ],
    "outputs": []
})

notebook["cells"] = cells

# Save notebook
notebook_path = app_path / "kaggle_notebook.ipynb"
with open(notebook_path, 'w') as f:
    json.dump(notebook, f, indent=2)

print(f"\n✅ Notebook created: {notebook_path}")

# Try to push via Kaggle API if connected
if kaggle_connected:
    print("\n🔑 Kaggle API connected - attempting to push...")
    
    try:
        # Create kernel-spec.json for Kaggle API
        kernel_spec = {
            "id": "",
            "title": f"{app_slug.replace('-', ' ').title()} - ML Training",
            "code_file": "kaggle_notebook.ipynb",
            "dataset_sources": [],
            "competition_source": "",
            "model_source": "",
            "kernel_type": "notebook",
            "language": "python",
            "enable_gpu": True,
            "enable_internet": True,
            "docker_image_type": "pytorch-gpu"
        }
        
        kernel_spec_path = app_path / "kernel-spec.json"
        with open(kernel_spec_path, 'w') as f:
            json.dump(kernel_spec, f, indent=2)
        
        print(f"✅ Kernel spec created: {kernel_spec_path}")
        print("\n📋 To push manually, run:")
        print(f"   cd {app_path}")
        print("   kaggle kernels push")
        print("\nOr upload the notebook at: https://www.kaggle.com/kernels")
        
    except Exception as e:
        print(f"⚠️  Could not create kernel spec: {e}")
else:
    print("\n⚠️  Kaggle API not connected")
    print("\n📋 To use this notebook:")
    print(f"1. Download: {notebook_path}")
    print("2. Upload to: https://www.kaggle.com/kernels")
    print("3. Or set KAGGLE_USERNAME and KAGGLE_KEY for auto-push")

# Create requirements file for ML
requirements_path = app_path / "ml_requirements.txt"
with open(requirements_path, 'w') as f:
    f.write("""# ML Training Requirements
pandas>=2.0.0
numpy>=1.24.0
scikit-learn>=1.3.0
matplotlib>=3.7.0
seaborn>=0.12.0
jupyter>=1.0.0
joblib>=1.3.0
""")

print(f"✅ ML requirements saved: {requirements_path}")

print("\n" + "=" * 50)
print("✅ ML Training Notebook Ready!")
print(f"\n📁 Notebook: {notebook_path.absolute()}")
print("🚀 Next: Upload to Kaggle and run with GPU")
